<a href="https://colab.research.google.com/github/santosdutrajoaogabriel-art/Pandas-transforma-o-e-manipula-o-de-dados/blob/main/json_normalize.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
pd.read_json('/content/informacoes.json')

   nome  idade                                          enderecos
0  João     28  {'tipo': 'casa', 'rua': 'Rua A', 'numero': 123...
1  João     28  {'tipo': 'trabalho', 'rua': 'Rua B', 'numero':...

In [3]:
import json

In [7]:
with open('informacoes.json') as f:
 json_main = json.load(f)

In [8]:
json_main

{'nome': 'João',
 'idade': 28,
 'enderecos': [{'tipo': 'casa',
   'rua': 'Rua A',
   'numero': 123,
   'cidade': 'São Paulo'},
  {'tipo': 'trabalho',
   'rua': 'Rua B',
   'numero': 456,
   'cidade': 'Rio de Janeiro'}]}

In [10]:
dados_normalizados = pd.json_normalize(json_main)

In [11]:
dados_normalizados

   nome  idade                                          enderecos
0  João     28  [{'tipo': 'casa', 'rua': 'Rua A', 'numero': 12...

In [15]:
dados_normalizados = pd.json_normalize(json_main, record_path='enderecos', meta = ['nome', 'idade'])

In [16]:
dados_normalizados

       tipo    rua  numero          cidade  nome idade
0      casa  Rua A     123       São Paulo  João    28
1  trabalho  Rua B     456  Rio de Janeiro  João    28