<a href="https://colab.research.google.com/github/santosdutrajoaogabriel-art/PANDAS_PYTHON/blob/main/notebooks/09_JSON/tratando_os_dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Sua tarefa é realizar alguns tratamentos e deixar esse arquivo JSON como um Pandas DataFrame, sem dados vazios e com a tipagem das colunas de forma correta. Como isso pode ser feito?

In [1]:
import pandas as pd

In [2]:
pd.read_json('/content/dados.json')

                                             pessoas
0  {'nome': 'João', 'idade': '25', 'endereco': {'...
1  {'nome': 'Maria', 'idade': 30, 'endereco': {'r...

In [3]:
import json

In [17]:
with open('dados.json', 'r') as f:
  json_main = json.load(f)

In [18]:
json_main

{'pessoas': [{'nome': 'João',
   'idade': '25',
   'endereco': {'rua': 'Rua A', 'numero': 123, 'cidade': 'São Paulo'},
   'telefones': ['11 1111-1111', '11 2222-2222']},
  {'nome': 'Maria',
   'idade': 30,
   'endereco': {'rua': '', 'numero': 456, 'cidade': 'Rio de Janeiro'},
   'telefones': ['21 3333-3333']}]}

In [19]:
df = pd.json_normalize(json_main, record_path='pessoas')

In [11]:
df

,nome,idade,telefones,endereco.rua,endereco.numero,endereco.cidade
0,João,25,"[11 1111-1111, 11 2222-2222]",Rua A,123,São Paulo
1,Maria,30,[21 3333-3333],,456,Rio de Janeiro

- identificando os tipos de colunas e se possui valores nulos.

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   nome             2 non-null      object
 1   idade            2 non-null      object
 2   telefones        2 non-null      object
 3   endereco.rua     2 non-null      object
 4   endereco.numero  2 non-null      int64
 5   endereco.cidade  2 non-null      object
dtypes: int64(1), object(5)
memory usage: 228.0+ bytes

In [20]:
df['idade'] = df['idade'].astype(int)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   nome             2 non-null      object
 1   idade            2 non-null      int64
 2   telefones        2 non-null      object
 3   endereco.rua     2 non-null      object
 4   endereco.numero  2 non-null      int64
 5   endereco.cidade  2 non-null      object
dtypes: int64(2), object(4)
memory usage: 228.0+ bytes

In [30]:
df['endereco.rua'].unique()

array(['Rua A', ''], dtype=object)

In [32]:
df_filtrado = df[df['endereco.rua'] != '']

In [33]:
df_filtrado

,nome,idade,telefones,endereco.rua,endereco.numero,endereco.cidade
0,João,25,"[11 1111-1111, 11 2222-2222]",Rua A,123,São Paulo