<a href="https://colab.research.google.com/github/santosdutrajoaogabriel-art/Pandas-transforma-o-e-manipula-o-de-dados/blob/main/Untitled11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
dados = pd.read_json('/content/dados_locacao_imoveis.json')

In [3]:
dados.head()

                                       dados_locacao
0  {'apartamento': 'A101 (blocoAP)', 'datas_combi...
1  {'apartamento': 'A102 (blocoAP)', 'datas_combi...
2  {'apartamento': 'B201 (blocoAP)', 'datas_combi...
3  {'apartamento': 'B202 (blocoAP)', 'datas_combi...
4  {'apartamento': 'C301 (blocoAP)', 'datas_combi...

In [4]:
dados.columns

Index(['dados_locacao'], dtype='object')

In [5]:
dados = pd.json_normalize(dados['dados_locacao'])

- Remover os dados em listas dentro do DataFrame;
- Verificar os tipos de dados;
- Identificar colunas numéricas;
- Transformar a coluna numérica para o tipo numérico.

In [6]:
colunas = list(dados.columns)
colunas

['apartamento',
 'datas_combinadas_pagamento',
 'datas_de_pagamento',
 'valor_aluguel']

In [7]:
dados = dados.explode(colunas[1:])
dados

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),01/06/2022,05/06/2022,"$ 1000,0 reais"
0,A101 (blocoAP),01/07/2022,03/07/2022,"$ 2500,0 reais"
1,A102 (blocoAP),02/06/2022,02/06/2022,"$ 1100,0 reais"
1,A102 (blocoAP),02/07/2022,06/07/2022,"$ 2600,0 reais"
2,B201 (blocoAP),03/06/2022,07/06/2022,"$ 1200,0 reais"
2,B201 (blocoAP),03/07/2022,03/07/2022,"$ 2700,0 reais"
3,B202 (blocoAP),04/06/2022,07/06/2022,"$ 1300,0 reais"
3,B202 (blocoAP),04/07/2022,05/07/2022,"$ 2800,0 reais"
4,C301 (blocoAP),05/06/2022,10/06/2022,"$ 1400,0 reais"
4,C301 (blocoAP),05/07/2022,09/07/2022,"$ 2900,0 reais"
5,C302 (blocoAP),06/06/2022,08/06/2022,"$ 1500,0 reais"
5,C302 (blocoAP),06/07/2022,12/07/2022,"$ 1200,0 reais"
6,D401 (blocoAP),07/06/2022,07/06/2022,"$ 1600,0 reais"
6,D401 (blocoAP),07/07/2022,09/07/2022,"$ 1300,0 reais"
7,D402 (blocoAP),08/06/2022,10/06/2022,"$ 1700,0 reais"
7,D402 (blocoAP),08/07/2022,14/07/2022,"$ 1400,0 reais"
8,E501 (blocoAP),09/06/2022,10/06/2022,"$ 1800,0 reais"
8,E501 (blocoAP),09/07/2022,09/07/2022,"$ 1500,0 reais"
9,E502 (blocoAP),10/06/2022,16/06/2022,"$ 1900,0 reais"
9,E502 (blocoAP),10/07/2022,12/07/2022,"$ 1600,0 reais"
10,F601 (blocoAP),11/06/2022,17/06/2022,"$ 2000,0 reais"
10,F601 (blocoAP),11/07/2022,13/07/2022,"$ 1000,0 reais"
11,F602 (blocoAP),12/06/2022,15/06/2022,"$ 2100,0 reais"
11,F602 (blocoAP),12/07/2022,12/07/2022,"$ 1100,0 reais"
12,G701 (blocoAP),13/06/2022,19/06/2022,"$ 2200,0 reais"
12,G701 (blocoAP),13/07/2022,20/07/2022,"$ 1200,0 reais"
13,G702 (blocoAP),14/06/2022,15/06/2022,"$ 2300,0 reais"
13,G702 (blocoAP),14/07/2022,17/07/2022,"$ 2100,0 reais"
14,H801 (blocoAP),15/06/2022,18/06/2022,"$ 2400,0 reais"
14,H801 (blocoAP),15/07/2022,16/07/2022,"$ 2200,0 reais"

In [8]:
dados.reset_index(inplace=True, drop=True)

In [9]:
dados.head()

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),01/06/2022,05/06/2022,"$ 1000,0 reais"
1,A101 (blocoAP),01/07/2022,03/07/2022,"$ 2500,0 reais"
2,A102 (blocoAP),02/06/2022,02/06/2022,"$ 1100,0 reais"
3,A102 (blocoAP),02/07/2022,06/07/2022,"$ 2600,0 reais"
4,B201 (blocoAP),03/06/2022,07/06/2022,"$ 1200,0 reais"

In [10]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     object
 2   datas_de_pagamento          30 non-null     object
 3   valor_aluguel               30 non-null     object
dtypes: object(4)
memory usage: 1.1+ KB

In [11]:
import numpy as np

In [12]:
dados['valor_aluguel'] = dados['valor_aluguel'].apply(lambda x: x.replace('$', '').replace(',', '.').replace('reais', '').strip().replace(' ', ''))
dados['valor_aluguel']

0     1000.0
1     2500.0
2     1100.0
3     2600.0
4     1200.0
5     2700.0
6     1300.0
7     2800.0
8     1400.0
9     2900.0
10    1500.0
11    1200.0
12    1600.0
13    1300.0
14    1700.0
15    1400.0
16    1800.0
17    1500.0
18    1900.0
19    1600.0
20    2000.0
21    1000.0
22    2100.0
23    1100.0
24    2200.0
25    1200.0
26    2300.0
27    2100.0
28    2400.0
29    2200.0
Name: valor_aluguel, dtype: object

In [13]:
dados['valor_aluguel'] = dados['valor_aluguel'].astype(np.float64)

In [14]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     object
 2   datas_de_pagamento          30 non-null     object
 3   valor_aluguel               30 non-null     float64
dtypes: float64(1), object(3)
memory usage: 1.1+ KB

- Buscando explicar a organização da identificação dos apartamentos, durante a criação do conjunto de dados, foi adicionado o texto (blocoAP). Esse texto informa que os nomes dos apartamentos estão organizados com a letra do bloco seguida do número do apartamento. No entanto, isso não traz nenhuma informação para nossos dados, sendo interessante realizar a remoção desse texto no conjunto de dados.

- Com isso, manipule os textos na coluna apartamento para remover o texto (blocoAP) do DataFrame.

In [15]:
dados.head()

      apartamento datas_combinadas_pagamento datas_de_pagamento  valor_aluguel
0  A101 (blocoAP)                 01/06/2022         05/06/2022         1000.0
1  A101 (blocoAP)                 01/07/2022         03/07/2022         2500.0
2  A102 (blocoAP)                 02/06/2022         02/06/2022         1100.0
3  A102 (blocoAP)                 02/07/2022         06/07/2022         2600.0
4  B201 (blocoAP)                 03/06/2022         07/06/2022         1200.0

In [16]:
dados['apartamento'] = dados['apartamento'].str.replace('\(blocoAP\)', ' ', regex=True)
dados.head()

<>:1: SyntaxWarning: invalid escape sequence '\('
<>:1: SyntaxWarning: invalid escape sequence '\('
/tmp/ipykernel_827/3788986114.py:1: SyntaxWarning: invalid escape sequence '\('
  dados['apartamento'] = dados['apartamento'].str.replace('\(blocoAP\)', ' ', regex=True)

  apartamento datas_combinadas_pagamento datas_de_pagamento  valor_aluguel
0      A101                   01/06/2022         05/06/2022         1000.0
1      A101                   01/07/2022         03/07/2022         2500.0
2      A102                   02/06/2022         02/06/2022         1100.0
3      A102                   02/07/2022         06/07/2022         2600.0
4      B201                   03/06/2022         07/06/2022         1200.0

- Nas colunas datas_de_pagamento e datas_combinadas_pagamento, temos datas em formato 'dia/mês/ano' (dd/mm/AAAA). Transforme esses dados para o tipo datetime e busque uma forma de visualização de subconjunto que possa contribuir no objetivo do contexto que os dados estão inseridos.

In [17]:
dados['datas_combinadas_pagamento'] = pd.to_datetime(dados['datas_combinadas_pagamento'], format='%d/%m/%Y')

In [18]:
dados['datas_de_pagamento'] = pd.to_datetime(dados['datas_de_pagamento'], format='%d/%m/%Y')

In [19]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     datetime64[ns]
 2   datas_de_pagamento          30 non-null     datetime64[ns]
 3   valor_aluguel               30 non-null     float64
dtypes: datetime64[ns](2), float64(1), object(1)
memory usage: 1.1+ KB

In [25]:
#contribuindo na solucao de contexto
dados['atraso'] = (dados['datas_de_pagamento'] - dados['datas_combinadas_pagamento'])

In [26]:
dados['atraso']

0    4 days
1    2 days
2    0 days
3    4 days
4    4 days
5    0 days
6    3 days
7    1 days
8    5 days
9    4 days
10   2 days
11   6 days
12   0 days
13   2 days
14   2 days
15   6 days
16   1 days
17   0 days
18   6 days
19   2 days
20   6 days
21   2 days
22   3 days
23   0 days
24   6 days
25   7 days
26   1 days
27   3 days
28   3 days
29   1 days
Name: atraso, dtype: timedelta64[ns]

In [28]:
media_atraso = dados.groupby(['apartamento'])['atraso'].mean()

In [29]:
media_atraso

apartamento
A101     3 days 00:00:00
A102     2 days 00:00:00
B201     2 days 00:00:00
B202     2 days 00:00:00
C301     4 days 12:00:00
C302     4 days 00:00:00
D401     1 days 00:00:00
D402     4 days 00:00:00
E501     0 days 12:00:00
E502     4 days 00:00:00
F601     4 days 00:00:00
F602     1 days 12:00:00
G701     6 days 12:00:00
G702     2 days 00:00:00
H801     2 days 00:00:00
Name: atraso, dtype: timedelta64[ns]