<a href="https://colab.research.google.com/github/santosdutrajoaogabriel-art/Pandas-transforma-o-e-manipula-o-de-dados/blob/main/Untitled10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import pandas as pd

In [25]:
dados = pd.read_json('/content/dados_vendas_clientes.json')

In [26]:
dados = pd.json_normalize(dados['dados_vendas'])

In [27]:
dados

,Data de venda,Cliente,Valor da compra
0,06/06/2022,"[@ANA _LUCIA 321, DieGO ARMANDIU 210, DieGO AR...","[R$ 836,5, R$ 573,33, R$ 392,8, R$ 512,34]"
1,07/06/2022,"[Isabely JOanes 738, Isabely JOanes 738, Isabe...","[R$ 825,31, R$ 168,07, R$ 339,18, R$ 314,69]"
2,08/06/2022,"[Isabely JOanes 738, JOãO Gabriel 671, Julya m...","[R$ 682,05, R$ 386,34, R$ 622,65, R$ 630,79]"
3,09/06/2022,"[Julya meireles 914, MaRIA Julia 444, MaRIA Ju...","[R$ 390,3, R$ 759,16, R$ 334,47, R$ 678,78]"
4,10/06/2022,"[MaRIA Julia 444, PEDRO PASCO 812, Paulo castr...","[R$ 314,24, R$ 311,15, R$ 899,16, R$ 885,24]"


- Remover os dados em listas dentro do DataFrame;
- Verificar os tipos de dados;
- Identificar colunas numéricas;
- Transformar a coluna numérica para o tipo numérico;

In [28]:
colunas = list(dados.columns)

In [29]:
colunas

['Data de venda', 'Cliente', 'Valor da compra']

In [30]:
dados = dados.explode(colunas[1:])

In [31]:
dados

  Data de venda             Cliente Valor da compra
0    06/06/2022     @ANA _LUCIA 321        R$ 836,5
0    06/06/2022  DieGO ARMANDIU 210       R$ 573,33
0    06/06/2022  DieGO ARMANDIU 210        R$ 392,8
0    06/06/2022  DieGO ARMANDIU 210       R$ 512,34
1    07/06/2022  Isabely JOanes 738       R$ 825,31
1    07/06/2022  Isabely JOanes 738       R$ 168,07
1    07/06/2022  Isabely JOanes 738       R$ 339,18
1    07/06/2022  Isabely JOanes 738       R$ 314,69
2    08/06/2022  Isabely JOanes 738       R$ 682,05
2    08/06/2022    JOãO Gabriel 671       R$ 386,34
2    08/06/2022  Julya meireles 914       R$ 622,65
2    08/06/2022  Julya meireles 914       R$ 630,79
3    09/06/2022  Julya meireles 914        R$ 390,3
3    09/06/2022     MaRIA Julia 444       R$ 759,16
3    09/06/2022     MaRIA Julia 444       R$ 334,47
3    09/06/2022     MaRIA Julia 444       R$ 678,78
4    10/06/2022     MaRIA Julia 444       R$ 314,24
4    10/06/2022     PEDRO PASCO 812       R$ 311,15
4    10/06/2022    Paulo castro 481       R$ 899,16
4    10/06/2022   Thiago fritzz 883       R$ 885,24

In [32]:
dados.reset_index(inplace=True, drop=True)

In [33]:
dados.head()

  Data de venda             Cliente Valor da compra
0    06/06/2022     @ANA _LUCIA 321        R$ 836,5
1    06/06/2022  DieGO ARMANDIU 210       R$ 573,33
2    06/06/2022  DieGO ARMANDIU 210        R$ 392,8
3    06/06/2022  DieGO ARMANDIU 210       R$ 512,34
4    07/06/2022  Isabely JOanes 738       R$ 825,31

- Verificar os tipos de dados;

In [34]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     object
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     object
dtypes: object(3)
memory usage: 612.0+ bytes

In [35]:
import numpy as np

In [36]:
dados['Valor da compra'] = dados['Valor da compra'].apply(lambda x : x.replace('R$', ' ').replace(',', '.').strip())

In [37]:
dados['Valor da compra'] = dados['Valor da compra'].astype(np.float64)

In [38]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     object
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     float64
dtypes: float64(1), object(2)
memory usage: 612.0+ bytes

- Devido a uma instabilidade no site da empresa, tivemos problemas com os nomes dos clientes durante o salvamento. Isso resultou em uma coluna de nomes de clientes com uma mistura de letras, maiúsculas e minúsculas, números e outros caracteres.

- Sabendo disso, manipule os textos presentes na coluna Cliente para que seja obtido como resultado os nomes dos clientes em letras minúsculas, com a ausência de caracteres especiais ou números.

In [39]:
dados.head()

  Data de venda             Cliente  Valor da compra
0    06/06/2022     @ANA _LUCIA 321           836.50
1    06/06/2022  DieGO ARMANDIU 210           573.33
2    06/06/2022  DieGO ARMANDIU 210           392.80
3    06/06/2022  DieGO ARMANDIU 210           512.34
4    07/06/2022  Isabely JOanes 738           825.31

In [40]:
dados['Cliente'].str.lower()

0        @ana _lucia 321
1     diego armandiu 210
2     diego armandiu 210
3     diego armandiu 210
4     isabely joanes 738
5     isabely joanes 738
6     isabely joanes 738
7     isabely joanes 738
8     isabely joanes 738
9       joão gabriel 671
10    julya meireles 914
11    julya meireles 914
12    julya meireles 914
13       maria julia 444
14       maria julia 444
15       maria julia 444
16       maria julia 444
17       pedro pasco 812
18      paulo castro 481
19     thiago fritzz 883
Name: Cliente, dtype: object

In [43]:
dados['Cliente'].str.replace('[^a-z]', '', regex=True)

0
1               ie
2               ie
3               ie
4       sabelyanes
5       sabelyanes
6       sabelyanes
7       sabelyanes
8       sabelyanes
9           abriel
10    ulyameireles
11    ulyameireles
12    ulyameireles
13           aulia
14           aulia
15           aulia
16           aulia
17
18      aulocastro
19     hiagofritzz
Name: Cliente, dtype: object

In [41]:
dados['Cliente'] = dados['Cliente'].str.replace('[^a-z]', ' ', regex=True).str.lower()
dados.head()

  Data de venda             Cliente  Valor da compra
0    06/06/2022                               836.50
1    06/06/2022   ie                          573.33
2    06/06/2022   ie                          392.80
3    06/06/2022   ie                          512.34
4    07/06/2022   sabely   anes               825.31

- Na coluna Data de venda, temos datas em formato 'dia/mês/ano' (dd/mm/AAAA). Transforme esses dados para o tipo datetime e busque uma forma de visualização de subconjunto que possa contribuir no objetivo do contexto que os dados estão inseridos

In [42]:
dados.head(15)

   Data de venda             Cliente  Valor da compra
0     06/06/2022                               836.50
1     06/06/2022   ie                          573.33
2     06/06/2022   ie                          392.80
3     06/06/2022   ie                          512.34
4     07/06/2022   sabely   anes               825.31
5     07/06/2022   sabely   anes               168.07
6     07/06/2022   sabely   anes               339.18
7     07/06/2022   sabely   anes               314.69
8     08/06/2022   sabely   anes               682.05
9     08/06/2022          abriel               386.34
10    08/06/2022   ulya meireles               622.65
11    08/06/2022   ulya meireles               630.79
12    09/06/2022   ulya meireles               390.30
13    09/06/2022      a     ulia               759.16
14    09/06/2022      a     ulia               334.47

In [47]:
dados['Data de venda'] = pd.to_datetime(dados['Data de venda'], format = '%d/%m/%Y')

In [48]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     datetime64[ns]
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     float64
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 612.0+ bytes

In [52]:
total_compra = dados.groupby(['Cliente'])['Valor da compra'].sum()

In [53]:
total_compra

Cliente
                     1147.65
     abriel           386.34
a     ulia           2086.65
aulo castro           899.16
hiago fritzz          885.24
ie                   1478.47
sabely   anes        2329.30
ulya meireles        1643.74
Name: Valor da compra, dtype: float64